### PR TITLE
fix the search function in the SearchModal

### LINKED ISSUE #192: fix(Search Bar) populate the search bar result with data from the DB

### PR DESCRIPTION
**Pull request by saidubundukamara**
closes #192

### CODE REVIEW

File: src/lib/SearchModal.svelte [hunk 1]
```diff
@@ -1,70 +1,45 @@
...
     loading = true;
     try {
-      // Simulated search - replace with actual API call
-      const mockProjects = [
-        { id: 1, name: 'Digital Health Initiative', description: 'Improving healthcare access' },
-        { id: 2, name: 'Education Technology Platform', description: 'Online learning solutions' },
-        { id: 3, name: 'Climate Action Tracker', description: 'Environmental monitoring system' }
-      ];
+      const response = await fetch(`/api/projects?term=${term}&page=1&limit=10`, {
+        method: 'GET',
```
Comment (sparrowsl) [inline src/lib/SearchModal.svelte:21]: since it's a `GET` request, we could leave out the 
```js
{ 
    method: "GET",
    headers: { "Content-Type": "application/json" }
}
```
but this works too.

**Review by sparrowsl — APPROVED** [review]

File: src/lib/SearchModal.svelte (hunk 1 above)
Comment (saidubundukamara) [reply src/lib/SearchModal.svelte:21]: Works, but now i'll have to urge to remove it in all GET requests lol
